# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Skyf
    Domain: skyfchain.io
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer


# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Operator1
    Domain: operator1.skyfchain.io
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  
  - Name: Customer1
    Domain: customer1.skyfchain.io
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Admin1
    Domain: admin1.skyfchain.io
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Monitor1
    Domain: monitor1.skyfchain.io
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
