version: '2'

services:

  orderer.skyfchain.io:
    container_name: orderer.skyfchain.io
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=SkyfMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/skyfchain.io/orderers/orderer.skyfchain.io/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/skyfchain.io/orderers/orderer.skyfchain.io/tls/:/var/hyperledger/orderer/tls
    - orderer.skyfchain.io:/var/hyperledger/production/orderer
    ports:
      - 127.0.0.1:7050:7050

  peer0.customer1.skyfchain.io:
    container_name: peer0.customer1.skyfchain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.customer1.skyfchain.io
      - CORE_PEER_ADDRESS=peer0.customer1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.customer1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customer1.skyfchain.io:7051
      - CORE_PEER_LOCALMSPID=Customer1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/customer1.skyfchain.io/peers/peer0.customer1.skyfchain.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/customer1.skyfchain.io/peers/peer0.customer1.skyfchain.io/tls:/etc/hyperledger/fabric/tls
        - peer0.customer1.skyfchain.io:/var/hyperledger/production
    ports:
      - 127.0.0.1:7051:7051
      - 127.0.0.1:7053:7053

  peer1.customer1.skyfchain.io:
    container_name: peer1.customer1.skyfchain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.customer1.skyfchain.io
      - CORE_PEER_ADDRESS=peer1.customer1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.customer1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.customer1.skyfchain.io:7051
      - CORE_PEER_LOCALMSPID=Customer1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/customer1.skyfchain.io/peers/peer1.customer1.skyfchain.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/customer1.skyfchain.io/peers/peer1.customer1.skyfchain.io/tls:/etc/hyperledger/fabric/tls
        - peer1.customer1.skyfchain.io:/var/hyperledger/production

    ports:
      - 127.0.0.1:8051:7051
      - 127.0.0.1:8053:7053

  peer0.operator1.skyfchain.io:
    container_name: peer0.operator1.skyfchain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.operator1.skyfchain.io
      - CORE_PEER_ADDRESS=peer0.operator1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.operator1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.operator1.skyfchain.io:7051
      - CORE_PEER_LOCALMSPID=Operator1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/operator1.skyfchain.io/peers/peer0.operator1.skyfchain.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/operator1.skyfchain.io/peers/peer0.operator1.skyfchain.io/tls:/etc/hyperledger/fabric/tls
        - peer0.operator1.skyfchain.io:/var/hyperledger/production
    ports:
      - 127.0.0.1:9051:7051
      - 127.0.0.1:9053:7053

  peer1.operator1.skyfchain.io:
    container_name: peer1.operator1.skyfchain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.operator1.skyfchain.io
      - CORE_PEER_ADDRESS=peer1.operator1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.operator1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.operator1.skyfchain.io:7051
      - CORE_PEER_LOCALMSPID=Operator1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/operator1.skyfchain.io/peers/peer1.operator1.skyfchain.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/operator1.skyfchain.io/peers/peer1.operator1.skyfchain.io/tls:/etc/hyperledger/fabric/tls
        - peer1.operator1.skyfchain.io:/var/hyperledger/production
    ports:
      - 127.0.0.1:10051:7051
      - 127.0.0.1:10053:7053

  peer0.admin1.skyfchain.io:
    container_name: peer0.admin1.skyfchain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.admin1.skyfchain.io
      - CORE_PEER_ADDRESS=peer0.admin1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.admin1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.admin1.skyfchain.io:7051
      - CORE_PEER_LOCALMSPID=Admin1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/admin1.skyfchain.io/peers/peer0.admin1.skyfchain.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/admin1.skyfchain.io/peers/peer0.admin1.skyfchain.io/tls:/etc/hyperledger/fabric/tls
        - peer0.admin1.skyfchain.io:/var/hyperledger/production
    ports:
      - 127.0.0.1:11051:7051
      - 127.0.0.1:11053:7053

  peer1.admin1.skyfchain.io:
    container_name: peer1.admin1.skyfchain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.admin1.skyfchain.io
      - CORE_PEER_ADDRESS=peer1.admin1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.admin1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.admin1.skyfchain.io:7051
      
      - CORE_PEER_LOCALMSPID=Admin1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/admin1.skyfchain.io/peers/peer1.admin1.skyfchain.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/admin1.skyfchain.io/peers/peer1.admin1.skyfchain.io/tls:/etc/hyperledger/fabric/tls
        - peer1.admin1.skyfchain.io:/var/hyperledger/production
    ports:
      - 127.0.0.1:12051:7051
      - 127.0.0.1:12053:7053

  peer0.monitor1.skyfchain.io:
    container_name: peer0.monitor1.skyfchain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.monitor1.skyfchain.io
      - CORE_PEER_ADDRESS=peer0.monitor1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.monitor1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.monitor1.skyfchain.io:7051
      - CORE_PEER_LOCALMSPID=Monitor1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/monitor1.skyfchain.io/peers/peer0.monitor1.skyfchain.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/monitor1.skyfchain.io/peers/peer0.monitor1.skyfchain.io/tls:/etc/hyperledger/fabric/tls
        - peer0.monitor1.skyfchain.io:/var/hyperledger/production
    ports:
      - 127.0.0.1:13051:7051
      - 127.0.0.1:13053:7053

  peer1.monitor1.skyfchain.io:
    container_name: peer1.monitor1.skyfchain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.monitor1.skyfchain.io
      - CORE_PEER_ADDRESS=peer1.monitor1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.monitor1.skyfchain.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.monitor1.skyfchain.io:7051
      - CORE_PEER_LOCALMSPID=Monitor1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/monitor1.skyfchain.io/peers/peer1.monitor1.skyfchain.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/monitor1.skyfchain.io/peers/peer1.monitor1.skyfchain.io/tls:/etc/hyperledger/fabric/tls
        - peer1.monitor1.skyfchain.io:/var/hyperledger/production
    ports:
      - 127.0.0.1:14051:7051
      - 127.0.0.1:14053:7053
